server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  security:
    jwt:
      keystore-location: keys/oauth2.jks
      keystore-password: 123456
      key-alias: oauth2-test
      private-key-passphrase: 123456